# Generated by Django 3.2.3 on 2021-06-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fultkitchen.ca%2Fproduct%2Frice-beans%2F&psig=AOvVaw1WQ53QAVuqx1XuUvu4_K8E&ust=1623360104789000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCNDwv_69i_ECFQAAAAAdAAAAABAJ', max_length=500),
        ),
    ]
