# Generated by Django 3.2.3 on 2021-06-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://ultkitchen.ca/wp-content/uploads/2018/08/food-image-placeholder.png', max_length=500),
        ),
    ]
